default:
  model:
    in_channels: 1
    out_channels: 1
    hidden_dim: 64
    kernel_size: 3
  optim:
    optimizer: AdamW
    scheduler: cosine
    batch_size: 32
    eval_batch_size: 32
    lr_initial: 1e-3
    lr_min: 5e-6
    warmup_steps: 1
    weight_decay: 0.01
    loss: BCELoss
    max_epochs: 30
